### PR TITLE
Added windows batch file for starting the server

### PR DESCRIPTION
**Pull request by UndefinedOffset**
Added a simple windows batch file for starting the server, only thing required really is that a java binary be on the system path. Pretty much identical to the .sh file for linux/mac.

### CODE REVIEW

**Comment by robbieaverill** [comment]
@UndefinedOffset fancy getting this into master?

**Comment by UndefinedOffset** [comment]
Wow this is a relic lol. But sure looks like it should work properly with master as well, it matches start.sh (plus a few windows specific stuff and minus some non-windows stuff). I'll double check that it works in the morning just to be sure and update.

**Comment by UndefinedOffset** [comment]
Wow this is a relic lol. But sure looks like it should work properly with master as well, it matches start.sh (plus a few windows specific stuff and minus some non-windows stuff). I'll double check that it works in the morning just to be sure and update.

**Comment by UndefinedOffset** [comment]
@robbieaverill that does work with the master branch I've updated the pull request to merge to master. I think that should work for merging it :S let me know if it doesn't/causes issues and I can open a new pull.

**Pull request merged**
